COMPILE_AND_RUN_LOCAL  = make compile && make run
COMPILE_AND_RUN_DOCKER = make compile && make up

system1_local:
	cd system1 && $(COMPILE_AND_RUN_LOCAL)

system1_docker: 
	cd system1 && $(COMPILE_AND_RUN_DOCKER)
